name: TonyStocco
favicon: null
layout_spectrum: 0.010498737450689077
typography_spectrum: 0.9172415744978935
title: Tony Stocco
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6623525968752801
  lightness: 0.16270823311060667
  saturation: 0.28341965447179973
  rhythmicContrast: 0.9196140537969768
purpose: []
