name: TonyStocco
favicon: null
layout_spectrum: 0.24758
typography_spectrum: 0.51538
title: Tony Stocco
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6d6d'
    - '#ffffff'
    - '#343232'
    - '#d0d0d0'
    - '#a2a2a2'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
